// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<ProjectE:item.pe_gem_armor_1>);
recipes.remove(<ProjectE:item.pe_gem_armor_2>);
recipes.remove(<ProjectE:item.pe_gem_armor_3>);
recipes.remove(<ProjectE:item.pe_gem_armor_0>);
recipes.remove(<ProjectE:item.pe_rm_armor_3>);
recipes.remove(<ProjectE:item.pe_rm_armor_2>);
recipes.remove(<ProjectE:item.pe_rm_armor_1>);
recipes.remove(<ProjectE:item.pe_rm_armor_0>);
recipes.remove(<ProjectE:item.pe_dm_armor_3>);
recipes.remove(<ProjectE:item.pe_dm_armor_2>);
recipes.remove(<ProjectE:item.pe_dm_armor_1>);
recipes.remove(<ProjectE:item.pe_dm_armor_0>);
recipes.remove(<ProjectE:item.pe_swrg>);
recipes.remove(<ProjectE:Transmutation Stone>);
recipes.remove(<StargateTech2:block.transportRing>);
recipes.remove(<minecraft:nether_star>);
recipes.remove(<ProjectE:item.pe_destruction_catalyst>);
recipes.remove(<ProjectE:item.pe_time_watch>);
recipes.remove(<warpbook:warppage>);
// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<ProjectE:item.pe_swrg>, [[<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>], [<minecraft:feather>, <ProjectE:item.pe_ring_iron_band>, <minecraft:feather>], [<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>]]);
recipes.removeShaped(<minecraft:clock>, [[null, <ore:ingotAluminumBrass>, null], [<ore:ingotAluminumBrass>, <ore:dustRedstone>, <ore:ingotAluminumBrass>], [null, <ore:ingotAluminumBrass>, null]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<ProjectE:item.pe_swrg>, [[<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>], [<minecraft:feather>, <ProjectE:item.pe_ring_iron_band>, <minecraft:feather>], [<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>]]);
recipes.addShaped(<ProjectE:item.pe_destruction_catalyst>, [[<ProjectE:Nova Cataclysm>, <ProjectE:item.pe_fuel:2>, <ProjectE:Nova Cataclysm>], [<ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_fuel:2>], [<ProjectE:Nova Cataclysm>, <ProjectE:item.pe_fuel:2>, <ProjectE:Nova Cataclysm>]]);
recipes.addShaped(<ProjectE:Transmutation Stone>, [[<ProjectE:item.pe_matter>, <minecraft:stone>, <ProjectE:item.pe_matter>], [<minecraft:stone>, <ProjectE:item.pe_philosophers_stone>, <minecraft:stone>], [<ProjectE:item.pe_matter>, <minecraft:stone>, <ProjectE:item.pe_matter>]]);
recipes.addShaped(<StargateTech2:block.transportRing>, [[null, <minecraft:stone>, null], [<StargateTech2:naquadah>, <ore:thermalexpansion:machineFrame>, <StargateTech2:naquadah>], [<StargateTech2:naquadah:2>, <StargateTech2:naquadah:5>, <StargateTech2:naquadah:2>]]);
recipes.addShaped(<minecraft:clock>, [[null, <ore:ingotGold>, null], [<minecraft:gold_ingot>, <minecraft:redstone>, <ore:ingotGold>], [null, <minecraft:gold_ingot>, null]]);
recipes.addShaped(<warpbook:warppage>, [[<minecraft:ender_eye>, <ore:ingotUnstable>, <minecraft:ender_eye>], [<ExtraUtilities:unstableingot>, <minecraft:paper>, <ore:ingotUnstable>], [<minecraft:ender_eye>, <ExtraUtilities:unstableingot>, <minecraft:ender_eye>]]);

