// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<securitycraft:trackMine>);
recipes.remove(<securitycraft:inventoryScanner>);
recipes.remove(<securitycraft:laserBlock>);
recipes.remove(<securitycraft:bouncingBetty>);
recipes.remove(<securitycraft:mine>);
recipes.remove(<securitycraft:keypad>);
recipes.remove(<securitycraft:null:2>);
recipes.remove(<securitycraft:null:1>);
recipes.remove(<securitycraft:null>);
recipes.remove(<securitycraft:codebreaker>);
recipes.remove(<DimensionalAnchors:chunkloader>);
recipes.remove(<MineFactoryReloaded:machine.2:10>);
recipes.remove(<ProjectE:item.pe_gem_armor_1>);
recipes.remove(<ProjectE:item.pe_gem_armor_2>);
recipes.remove(<ProjectE:item.pe_gem_armor_3>);
recipes.remove(<ProjectE:item.pe_gem_armor_0>);
recipes.remove(<ProjectE:item.pe_rm_armor_3>);
recipes.remove(<ProjectE:item.pe_rm_armor_2>);
recipes.remove(<ProjectE:item.pe_rm_armor_1>);
recipes.remove(<ProjectE:item.pe_rm_armor_0>);
recipes.remove(<ProjectE:item.pe_dm_armor_3>);
recipes.remove(<ProjectE:item.pe_dm_armor_2>);
recipes.remove(<ProjectE:item.pe_dm_armor_1>);
recipes.remove(<ProjectE:item.pe_dm_armor_0>);
recipes.remove(<ProjectE:item.pe_swrg>);
recipes.remove(<ProjectE:Transmutation Stone>);
recipes.remove(<StargateTech2:block.transportRing>);
recipes.remove(<minecraft:nether_star>);
recipes.remove(<ProjectE:item.pe_destruction_catalyst>);
recipes.remove(<ProjectE:item.pe_time_watch>);
recipes.remove(<warpbook:warppage>);
// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<ProjectE:item.pe_swrg>, [[<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>], [<minecraft:feather>, <ProjectE:item.pe_ring_iron_band>, <minecraft:feather>], [<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>]]);
recipes.removeShaped(<minecraft:clock>, [[null, <ore:ingotAluminumBrass>, null], [<ore:ingotAluminumBrass>, <ore:dustRedstone>, <ore:ingotAluminumBrass>], [null, <ore:ingotAluminumBrass>, null]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<securitycraft:trackMine>, [[<ore:ingotIron>, <securitycraft:mine>, <ore:ingotIron>], [<ore:ingotIron>, <ore:woodStick>, <ore:ingotIron>], [<ore:ingotIron>, <securitycraft:mine>, <ore:ingotIron>]]);
recipes.addShaped(<securitycraft:inventoryScanner>, [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>], [<minecraft:stone>, <securitycraft:laserBlock>, <minecraft:stone>], [<minecraft:stone>, <EnderStorage:enderChest>, <minecraft:stone>]]);
recipes.addShaped(<securitycraft:laserBlock>, [[<ore:stone>, <minecraft:glass>, <ore:stone>], [<minecraft:glass>, <ore:blockRedstone>, <minecraft:glass>], [<ore:stone>, <ore:blockGlassColorless>, <ore:stone>]]);
recipes.addShaped(<securitycraft:bouncingBetty>, [[<ore:ingotIron>, <minecraft:heavy_weighted_pressure_plate>, <ore:ingotIron>], [<ore:ingotIron>, <securitycraft:mine>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<securitycraft:mine>, [[<minecraft:stone>, <minecraft:iron_ingot>, <minecraft:stone>], [<minecraft:iron_ingot>, <ProjectE:Nova Cataclysm>, <minecraft:iron_ingot>], [<minecraft:stone>, <minecraft:iron_ingot>, <minecraft:stone>]]);
recipes.addShaped(<securitycraft:keypad>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<minecraft:iron_ingot>, <minecraft:stone_button>, <ore:ingotIron>], [<minecraft:iron_ingot>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<securitycraft:null:2>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<securitycraft:null:1>, <securitycraft:null:1>, <securitycraft:null:1>]]);
recipes.addShaped(<securitycraft:null:1>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<securitycraft:null>, <securitycraft:null>, <securitycraft:null>]]);
recipes.addShaped(<securitycraft:null>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <ore:ingotIron>], [<minecraft:gold_ingot>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.addShaped(<DimensionalAnchors:chunkloader>, [[<ore:blockGold>, <ore:blockGold>, <ore:blockGold>], [<ore:blockGold>, <ore:blockIron>, <ore:blockGold>], [<minecraft:gold_block>, <minecraft:gold_block>, <ore:blockGold>]]);
recipes.addShaped(<ProjectE:item.pe_swrg>, [[<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>], [<minecraft:feather>, <ProjectE:item.pe_ring_iron_band>, <minecraft:feather>], [<ProjectE:item.pe_matter:1>, <minecraft:feather>, <ProjectE:item.pe_matter:1>]]);
recipes.addShaped(<ProjectE:item.pe_destruction_catalyst>, [[<ProjectE:Nova Cataclysm>, <ProjectE:item.pe_fuel:2>, <ProjectE:Nova Cataclysm>], [<ProjectE:item.pe_fuel:2>, <ProjectE:item.pe_matter:1>, <ProjectE:item.pe_fuel:2>], [<ProjectE:Nova Cataclysm>, <ProjectE:item.pe_fuel:2>, <ProjectE:Nova Cataclysm>]]);
recipes.addShaped(<ProjectE:Transmutation Stone>, [[<ProjectE:item.pe_matter>, <minecraft:stone>, <ProjectE:item.pe_matter>], [<minecraft:stone>, <ProjectE:item.pe_philosophers_stone>, <minecraft:stone>], [<ProjectE:item.pe_matter>, <minecraft:stone>, <ProjectE:item.pe_matter>]]);
recipes.addShaped(<StargateTech2:block.transportRing>, [[null, <minecraft:stone>, null], [<StargateTech2:naquadah>, <ore:thermalexpansion:machineFrame>, <StargateTech2:naquadah>], [<StargateTech2:naquadah:2>, <StargateTech2:naquadah:5>, <StargateTech2:naquadah:2>]]);
recipes.addShaped(<minecraft:clock>, [[null, <ore:ingotGold>, null], [<minecraft:gold_ingot>, <minecraft:redstone>, <ore:ingotGold>], [null, <minecraft:gold_ingot>, null]]);
recipes.addShaped(<warpbook:warppage>, [[<minecraft:ender_eye>, <ore:ingotUnstable>, <minecraft:ender_eye>], [<ExtraUtilities:unstableingot>, <minecraft:paper>, <ore:ingotUnstable>], [<minecraft:ender_eye>, <ExtraUtilities:unstableingot>, <minecraft:ender_eye>]]);

